name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: ['20.x', '22.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        if: matrix.node-version == '20.x'
        run: npm run lint
      - name: Types
        if: matrix.node-version == '20.x'
        run: node_modules/.bin/tsc
      - name: Prettier
        if: matrix.node-version == '20.x'
        run: npm run prettier:check
      - name: Build
        if: matrix.node-version == '20.x'
        run: npm run build
      - name: Test
        run: npm test
      - name: Integration
        run: npm run test:integration
